language: r
dist: xenial
latex: false

branches:
  only:
    - master

cache:
  packages: yes
  directories:
    - $HOME/bin

addons:
  ssh_known_hosts: datapleth.io

before_install:
- openssl aes-256-cbc -K $encrypted_04551ded9036_key -iv $encrypted_04551ded9036_iv
  -in deploy-key.enc -out deploy-key -d

script:
  - Rscript -e 'blogdown::install_hugo()'
  - Rscript -e 'blogdown::build_site()'
  

