language: r
dist: xenial
latex: false

branches:
  only:
    - master

cache:
  packages: yes
  directories:
    - $HOME/bin

addons:
  ssh_known_hosts: 
  - datapleth.io
  - 188.166.216.253

before_install:
- bash _scripts/install.sh

script:
  - Rscript -e 'install.packages(c("maptools","rgeos","gpclib","foreign","sp"))'
  - Rscript -e 'install.packages(c("ggplot2","plyr","dplyr"))'
  - Rscript -e 'blogdown::install_hugo()'
  - Rscript -e 'blogdown::build_site()'
  
after_success:
  - bash _scripts/deploy.sh
