language: r
dist: bionic
latex: false

branches:
  only:
    - master

sudo: required

apt_packages:
- default-jre
- default-jdk
- fonts-wqy-zenhei
- fonts-arphic-bkai00mp fonts-arphic-bsmi00lp fonts-arphic-gbsn00lp
- fonts-arphic-gkai00mp fonts-arphic-ukai fonts-arphic-uming fonts-cns11643-kai
- fonts-cns11643-sung fonts-cwtex-fs fonts-cwtex-heib fonts-cwtex-kai
- fonts-cwtex-ming fonts-cwtex-yen
- libgdal-dev libproj-dev


cache:
  packages: yes
  directories:
    - $HOME/bin

addons:
  ssh_known_hosts: 
  - datapleth.io
  - 188.166.216.253

before_install:
- bash _scripts/install.sh



script:
  - Rscript -e 'install.packages(c("maptools","maps","rgeos","gpclib","foreign","sp"))'
  - Rscript -e 'install.packages(c("ggplot2","plyr","dplyr", "reshape2", "stringdist"))'
  - Rscript -e 'install.packages(c("RCurl", "Amelia", "rgdal", "jsonlite"))'
  - Rscript -e 'install.packages(c("rJava", "OpenStreetMap", "rvest", "grid"))'
  - Rscript -e 'install.packages(c("lubridate", "data.table", "ggthemes"))'
  - Rscript -e 'blogdown::install_hugo()'
  - Rscript -e 'blogdown::build_site()'
  
after_success:
  - bash _scripts/deploy.sh
