language: r
dist: xenial
latex: false

branches:
  only:
    - master

cache:
  packages: yes
  directories:
    - $HOME/bin

addons:
  ssh_known_hosts: datapleth.io

before_install:
- bash _scripts/install.sh

script:
  - Rscript -e 'blogdown::install_hugo()'
  - Rscript -e 'blogdown::build_site()'
  
after_success:
  - bash _scripts/deploy.sh
