baseURL = "https://datapleth.io/"
languageCode = "en-us"
title = "Datapleth theme"
theme = "datapleth-theme"
relativeURLs = true

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "We solve your problems with your data."
    meta_og_title = "datapleth.io"
    meta_og_type = "website"
    meta_og_url = "https://datapleth.io"
    meta_og_image = "./logos/datapleth_white.svg"
    meta_og_description = "We solve your problems with your data."
    meta_twitter_card = "summary"
    meta_twitter_site = "@barthLong"
    meta_twitter_creator = "@barthLong"

[[menu.main]]
	name = "Blog"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
